/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.gacimora.pizzarestclient.gui;

import cz.gacimora.pizzarestclient.CustomerClient;
import cz.gacimora.pizzarestclient.entities.Customer;
import cz.gacimora.pizzarestclient.entities.Customers;
import cz.gacimora.pizzarestclient.entities.Pizza;
import cz.gacimora.pizzarestclient.entities.PizzaOrder;
import java.util.ArrayList;
import java.util.List;
import javax.ws.rs.ClientErrorException;

/**
 *
 * @author gacimora
 */
public class GuiRunner extends javax.swing.JFrame {

    /**
     * Creates new form ClientRunner
     */
    public GuiRunner() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1_URI = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1_output = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jTextField1_QueryID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        FindByCustomerId = new javax.swing.JButton();
        UpdateCustomer = new javax.swing.JButton();
        ClearForm = new javax.swing.JButton();
        DeleteRecord = new javax.swing.JButton();
        CreateRecord = new javax.swing.JButton();
        FindAllRecords = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1_CustomerId = new javax.swing.JTextField();
        jTextField1_FirstName = new javax.swing.JTextField();
        jTextField1_Surname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField1_PizzaName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField1_PizzaPrice = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField1_OrderId = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("URL"));

        jLabel1.setText("Set remote URL");

        jTextField1_URI.setText("http://localhost:18195/PizzaService/webresources");
        jTextField1_URI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_URIActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1_URI, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1_URI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextArea1_output.setColumns(20);
        jTextArea1_output.setRows(5);
        jScrollPane1.setViewportView(jTextArea1_output);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Operation"));

        jTextField1_QueryID.setText("1");
        jTextField1_QueryID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_QueryIDActionPerformed(evt);
            }
        });

        jLabel2.setText("customer ID");

        FindByCustomerId.setText("Find");
        FindByCustomerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindByCustomerIdActionPerformed(evt);
            }
        });

        UpdateCustomer.setText("Update");
        UpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateCustomerActionPerformed(evt);
            }
        });

        ClearForm.setText("Clear Form");
        ClearForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearFormActionPerformed(evt);
            }
        });

        DeleteRecord.setText("Delete Record");
        DeleteRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteRecordActionPerformed(evt);
            }
        });

        CreateRecord.setText("Create Record");
        CreateRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateRecordActionPerformed(evt);
            }
        });

        FindAllRecords.setText("Find All Records");
        FindAllRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindAllRecordsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1_QueryID, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ClearForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FindByCustomerId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CreateRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(UpdateCustomer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DeleteRecord, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FindAllRecords, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1_QueryID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FindByCustomerId)
                    .addComponent(FindAllRecords))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CreateRecord)
                    .addComponent(UpdateCustomer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClearForm)
                    .addComponent(DeleteRecord))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jLabel3.setText("Customer ID");

        jLabel4.setText("FirstName");

        jLabel5.setText("Surname");

        jTextField1_CustomerId.setEditable(false);
        jTextField1_CustomerId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_CustomerIdActionPerformed(evt);
            }
        });

        jTextField1_FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_FirstNameActionPerformed(evt);
            }
        });

        jTextField1_Surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_SurnameActionPerformed(evt);
            }
        });

        jLabel6.setText("PizzaName");

        jTextField1_PizzaName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_PizzaNameActionPerformed(evt);
            }
        });

        jLabel7.setText("Pizza Price");

        jTextField1_PizzaPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_PizzaPriceActionPerformed(evt);
            }
        });

        jLabel8.setText("Order Id");

        jTextField1_OrderId.setEditable(false);
        jTextField1_OrderId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1_OrderIdActionPerformed(evt);
            }
        });

        jLabel9.setText("Message Output");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7))
                                    .addGap(43, 43, 43)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField1_PizzaName, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField1_PizzaPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextField1_OrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField1_CustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField1_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField1_Surname, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(264, 264, 264))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1_CustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1_Surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1_OrderId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1_PizzaName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1_PizzaPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FindByCustomerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindByCustomerIdActionPerformed
        ClearFormValues();
        CustomerClient restClient = new CustomerClient();
        String custID = this.jTextField1_QueryID.getText();
        try {
            Customer result = restClient.find_JSON(Customer.class, custID);
            this.jTextArea1_output.setText(result.toString());
            this.jTextField1_CustomerId.setText(result.getId().toString());
            this.jTextField1_FirstName.setText(result.getName());
            this.jTextField1_Surname.setText(result.getSurname());
            if (!result.getMyOrders().isEmpty()) {
                this.jTextField1_OrderId.setText(result.getMyOrders().get(0).getId().toString());
                if (!result.getMyOrders().get(0).getOrderedPizzas().isEmpty()) {
                    this.jTextField1_PizzaName.setText(result.getMyOrders().get(0).getOrderedPizzas().get(0).getName());
                    this.jTextField1_PizzaPrice.setText(result.getMyOrders().get(0).getOrderedPizzas().get(0).getPrice());
                }
            }
        } catch (Exception e) {
            this.jTextArea1_output.setText("Error when loading the customer record.");
        }


    }//GEN-LAST:event_FindByCustomerIdActionPerformed

    private void jTextField1_URIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_URIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_URIActionPerformed

    private void jTextField1_QueryIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_QueryIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_QueryIDActionPerformed

    private void jTextField1_CustomerIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_CustomerIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_CustomerIdActionPerformed

    private void jTextField1_FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_FirstNameActionPerformed

    private void jTextField1_SurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_SurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_SurnameActionPerformed

    private void jTextField1_PizzaNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_PizzaNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_PizzaNameActionPerformed

    private void jTextField1_PizzaPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_PizzaPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_PizzaPriceActionPerformed

    private void jTextField1_OrderIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1_OrderIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1_OrderIdActionPerformed

    private void UpdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateCustomerActionPerformed
        CustomerClient restClient = new CustomerClient();
        String id = this.jTextField1_CustomerId.getText();

        try {
            Customer existingCustomer = restClient.find_JSON(Customer.class, id);
            existingCustomer.setName(this.jTextField1_FirstName.getText());
            existingCustomer.setSurname(this.jTextField1_Surname.getText());
            existingCustomer.getMyOrders().get(0).getOrderedPizzas().get(0).setName(this.jTextField1_PizzaName.getText());
            existingCustomer.getMyOrders().get(0).getOrderedPizzas().get(0).setPrice(this.jTextField1_PizzaPrice.getText());
            restClient.edit_JSON(existingCustomer, id);
            ClearFormValues();
            this.jTextArea1_output.setText("Customer record updated successfully");
        } catch (Exception e) {
            this.jTextArea1_output.setText("Customer record update failed with exception: " + e.toString());
        }
    }//GEN-LAST:event_UpdateCustomerActionPerformed

    private void ClearFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearFormActionPerformed
        ClearFormValues();
    }//GEN-LAST:event_ClearFormActionPerformed

    private void ClearFormValues() {
        this.jTextArea1_output.setText("");
        this.jTextField1_CustomerId.setText("");
        this.jTextField1_FirstName.setText("");
        this.jTextField1_Surname.setText("");
        this.jTextField1_OrderId.setText("");
        this.jTextField1_PizzaName.setText("");
        this.jTextField1_PizzaPrice.setText("");
    }

    public static boolean IsNullOrEmpty(String str) {
        if (str != null && !str.isEmpty()) {
            return false;
        }
        return true;
    }

    private static String GetAllCustomers(CustomerClient restClient) throws ClientErrorException {
        StringBuilder outputMessage = new StringBuilder();  
        outputMessage.append("Number of records found: " + restClient.countREST() + "\r\n");
        outputMessage.append("********** Start of customer list ************\r\n");        
        Customers customers = restClient.findAllCustomers_XML(Customers.class);
        for (Customer customer : customers.getCustomers()) {
            outputMessage.append("id: " + customer.getId() + ", name: " + customer.getName() + ", surname: " + customer.getSurname() + "\r\n");            
        }
        outputMessage.append("********** End of customer list ************\r\n");        
        return outputMessage.toString();
    }

    private void DeleteRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteRecordActionPerformed
        CustomerClient restClient = new CustomerClient();
        try {
            restClient.remove(this.jTextField1_QueryID.getText());
            ClearFormValues();
            this.jTextArea1_output.setText("Customer record deleted successfully");            
        } catch (Exception e) {
            this.jTextArea1_output.setText("Deleting customer record failed with exception: " + e.toString());
        }
    }//GEN-LAST:event_DeleteRecordActionPerformed

    private void CreateRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateRecordActionPerformed
        CustomerClient restClient = new CustomerClient();

        Customer newCustomer = new Customer();
        String firstName = this.jTextField1_FirstName.getText();
        String surname = this.jTextField1_Surname.getText();
        String pizzaName = this.jTextField1_PizzaName.getText();
        String pizzaPrice = this.jTextField1_PizzaPrice.getText();

        try {
            // creating customer
            if (IsNullOrEmpty(firstName) || IsNullOrEmpty(surname) || IsNullOrEmpty(pizzaName) || IsNullOrEmpty(pizzaPrice)) {
                throw new IllegalArgumentException("Some arguments for new record are null or empty.");
            }
            newCustomer.setName(firstName);
            newCustomer.setSurname(surname);
            newCustomer.setMyOrders(new ArrayList<PizzaOrder>());

            // creating list of ordered pizzas
            Pizza pizza = new Pizza(pizzaName, pizzaPrice);
            List<Pizza> orderedPizzas = new ArrayList<Pizza>();
            orderedPizzas.add(pizza);

            // assign list of pizzas to the customer order
            newCustomer.getMyOrders().add(new PizzaOrder(orderedPizzas));

            restClient.create_JSON(newCustomer);
            ClearFormValues();
            this.jTextArea1_output.setText("Customer created successfully");
        } catch (Exception e) {
            this.jTextArea1_output.setText("Creating customer record failed with exception: " + e.toString());
        }
    }//GEN-LAST:event_CreateRecordActionPerformed

    private void FindAllRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindAllRecordsActionPerformed
        CustomerClient restClient = new CustomerClient();
        this.jTextArea1_output.setText(GetAllCustomers(restClient));
    }//GEN-LAST:event_FindAllRecordsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiRunner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiRunner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiRunner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiRunner.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiRunner().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearForm;
    private javax.swing.JButton CreateRecord;
    private javax.swing.JButton DeleteRecord;
    private javax.swing.JButton FindAllRecords;
    private javax.swing.JButton FindByCustomerId;
    private javax.swing.JButton UpdateCustomer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1_output;
    private javax.swing.JTextField jTextField1_CustomerId;
    private javax.swing.JTextField jTextField1_FirstName;
    private javax.swing.JTextField jTextField1_OrderId;
    private javax.swing.JTextField jTextField1_PizzaName;
    private javax.swing.JTextField jTextField1_PizzaPrice;
    private javax.swing.JTextField jTextField1_QueryID;
    private javax.swing.JTextField jTextField1_Surname;
    private javax.swing.JTextField jTextField1_URI;
    // End of variables declaration//GEN-END:variables
}
